/*
	***DO NOT EDIT THIS FILE!!!***
	This java file is intended to be used with the mortgage file
 */
public class Dollar 
{
	//truncate the number into the following parts
	private int numMillion;
	private int numThousand;
	private int numDollars;
	private int numCents;
	
	public Dollar() //empty constructor
	{
		numMillion=0;
		numThousand=0;
		numDollars=0;
		numCents=0;
	}
	public Dollar (double input)//constructor
	{
		try
		{
			if(input<0)//input must be greater than 0.
			{
				throw new Exception();
			}
			else
			{
				numCents= (int)((Math.round(input*100))%100);
				int in=(int)input;
				if (in<1000000)//less than one Million
				{
					numMillion=0;
					if (in<1000)//less than one thousand
					{
						numThousand=0;
						if(in<1)//less than one dollar
						{
							numDollars=0;
						}
						else//more than or equal one dollar
						{
							numDollars=in;
						}
					}
					else //more than or equal one thousand
					{
						numThousand=in/1000;
						numDollars=in%1000;
					}
				}
				else// greater than or equal a Million
				{
					numMillion=in/1000000;
					numThousand=(in%1000000)/1000;
					numDollars=in%1000;
				}
			}
		}
		catch (Exception ex)
		{
			System.out.print("You do not owe Money!");
		}
	}
	public String toString()
	{
		String millionString="";
		String thousandString="";
		String dollarString="";
		String centsString="";
		
		//convert int to string
		millionString=Integer.toString(numMillion);
		if (numMillion>0)
		{
			if(numThousand<100)
			{
				if(numThousand<10)//1,003,000
				{
					thousandString="00"+Integer.toString(numThousand);
				}
				else//1,023,000
				{
					thousandString="0"+Integer.toString(numThousand);
				}
			}
			else//1,223,000
			{
				thousandString=Integer.toString(numThousand);
			}
		}
		else//between a thousand and a million (223,000)
		{
			thousandString=Integer.toString(numThousand);
		}
		
		if(numThousand>0||numMillion>0)
		{
			if(numDollars<100)
			{
				if(numDollars<10)//1,003
				{
					dollarString="00"+Integer.toString(numDollars);
				}
				else//1,023
				{
					dollarString="0"+Integer.toString(numDollars);
				}
			}
			else //1,223
			{
				dollarString=Integer.toString(numDollars);
			}
		}
		else //223
		{
			dollarString=Integer.toString(numDollars);
		}
		
		if(numCents<10)
		{
			centsString="0"+Integer.toString(numCents);			}
		else
		{
			centsString=Integer.toString(numCents);
		}

		//returning if/else
		if (numMillion>0)//greater than or equal a million 12,234,456.78
		{
			return ("$" + millionString +","+ thousandString +","+ dollarString +"."+ centsString);
		}
		else//less than a million
		{
			if (numThousand>0)//greater than or equal a thousand 12,234.67
			{
				return String.format("$"+ thousandString +","+ dollarString +"."+ centsString);
			}
			else//less than a thousand 12.30
			{
					return String.format("$" + dollarString +"."+centsString);
			}
		}
	}
}
